/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as DemandasNovaRouteImport } from './routes/demandas.nova'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiPublicHooksEmailEmAnaliseRouteImport } from './routes/api/public/hooks/email-em-analise'
import { Route as ApiPublicHooksEmailDailyRouteImport } from './routes/api/public/hooks/email-daily'
import { Route as ApiPublicHooksEmailAssignmentRouteImport } from './routes/api/public/hooks/email-assignment'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const DemandasNovaRoute = DemandasNovaRouteImport.update({
  id: '/demandas/nova',
  path: '/demandas/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEmailEmAnaliseRoute =
  ApiPublicHooksEmailEmAnaliseRouteImport.update({
    id: '/api/public/hooks/email-em-analise',
    path: '/api/public/hooks/email-em-analise',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEmailDailyRoute =
  ApiPublicHooksEmailDailyRouteImport.update({
    id: '/api/public/hooks/email-daily',
    path: '/api/public/hooks/email-daily',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEmailAssignmentRoute =
  ApiPublicHooksEmailAssignmentRouteImport.update({
    id: '/api/public/hooks/email-assignment',
    path: '/api/public/hooks/email-assignment',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/demandas/nova': typeof DemandasNovaRoute
  '/api/public/hooks/email-assignment': typeof ApiPublicHooksEmailAssignmentRoute
  '/api/public/hooks/email-daily': typeof ApiPublicHooksEmailDailyRoute
  '/api/public/hooks/email-em-analise': typeof ApiPublicHooksEmailEmAnaliseRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/demandas/nova': typeof DemandasNovaRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/email-assignment': typeof ApiPublicHooksEmailAssignmentRoute
  '/api/public/hooks/email-daily': typeof ApiPublicHooksEmailDailyRoute
  '/api/public/hooks/email-em-analise': typeof ApiPublicHooksEmailEmAnaliseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/demandas/nova': typeof DemandasNovaRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/email-assignment': typeof ApiPublicHooksEmailAssignmentRoute
  '/api/public/hooks/email-daily': typeof ApiPublicHooksEmailDailyRoute
  '/api/public/hooks/email-em-analise': typeof ApiPublicHooksEmailEmAnaliseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/demandas/nova'
    | '/api/public/hooks/email-assignment'
    | '/api/public/hooks/email-daily'
    | '/api/public/hooks/email-em-analise'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/demandas/nova'
    | '/'
    | '/api/public/hooks/email-assignment'
    | '/api/public/hooks/email-daily'
    | '/api/public/hooks/email-em-analise'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/demandas/nova'
    | '/_authenticated/'
    | '/api/public/hooks/email-assignment'
    | '/api/public/hooks/email-daily'
    | '/api/public/hooks/email-em-analise'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DemandasNovaRoute: typeof DemandasNovaRoute
  ApiPublicHooksEmailAssignmentRoute: typeof ApiPublicHooksEmailAssignmentRoute
  ApiPublicHooksEmailDailyRoute: typeof ApiPublicHooksEmailDailyRoute
  ApiPublicHooksEmailEmAnaliseRoute: typeof ApiPublicHooksEmailEmAnaliseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/demandas/nova': {
      id: '/demandas/nova'
      path: '/demandas/nova'
      fullPath: '/demandas/nova'
      preLoaderRoute: typeof DemandasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/email-em-analise': {
      id: '/api/public/hooks/email-em-analise'
      path: '/api/public/hooks/email-em-analise'
      fullPath: '/api/public/hooks/email-em-analise'
      preLoaderRoute: typeof ApiPublicHooksEmailEmAnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/email-daily': {
      id: '/api/public/hooks/email-daily'
      path: '/api/public/hooks/email-daily'
      fullPath: '/api/public/hooks/email-daily'
      preLoaderRoute: typeof ApiPublicHooksEmailDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/email-assignment': {
      id: '/api/public/hooks/email-assignment'
      path: '/api/public/hooks/email-assignment'
      fullPath: '/api/public/hooks/email-assignment'
      preLoaderRoute: typeof ApiPublicHooksEmailAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DemandasNovaRoute: DemandasNovaRoute,
  ApiPublicHooksEmailAssignmentRoute: ApiPublicHooksEmailAssignmentRoute,
  ApiPublicHooksEmailDailyRoute: ApiPublicHooksEmailDailyRoute,
  ApiPublicHooksEmailEmAnaliseRoute: ApiPublicHooksEmailEmAnaliseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
